steps:
# test using mvaven
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ["test"]
# build using maven
- name: 'maven:3-jdk-8'
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']
# build the container
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/example-app2-java', '--build-arg=JAR_FILE=target/example-app-java-0.0.1-SNAPSHOT.jar', '.']
# push the image to GCR
images: ["gcr.io/$PROJECT_ID/example-app2-java"]

