apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-java
spec:
  selector:
    matchLabels:
      app: hello-world-java
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:   # create pods using pod definition in this template
    metadata:
      labels:
        app: hello-world-java
    spec:
      containers:
      - name: hello-world-java
        image: gcr.io/rranthos/hello-app-java:v1
        ports:
        - containerPort: 8080
          name: server
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-java-ingress
spec:
  type: LoadBalancer
  selector:
    app: hello-world-java
  ports:
  - name: http
    port: 80
    targetPort: 8080
  loadBalancerIP: 10.0.10.10
