apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-java-l7 
  namespace: default
spec:
  rules:
    - host: helloworld.k8s.rick-ross.com
      http:
        paths:
          - backend:
              serviceName: hello-world-java-ingress 
              servicePort: 80

