steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder', '--verbose', 'gcr.io/$PROJECT_ID/example-dotnet-core-app']
  dir: example-dotnet-core-app
images: ["gcr.io/$PROJECT_ID/example-dotnet-core-app"]
