steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder', '--verbose', 'gcr.io/$PROJECT_ID/example-go-app']
  dir: example-go-app
images: ["gcr.io/$PROJECT_ID/example-go-app"]
